<?php
$labels = array();
$labels['caldavzap'] = 'Kalender';
$labels['todo'] = 'Aufgaben';
$labels['reload'] = 'Aktualisieren';

$labels['cdz_standardview'] = 'Standardansicht';
$labels['cdz_weekstart'] = 'Erster Wochentag';
$labels['cdz_worktime'] = 'Arbeitszeit';
$labels['cdz_weekendays'] = 'Wochenende';

$labels['cdz_month'] = 'Monat';
$labels['cdz_multiWeek'] = 'Wochen';
$labels['cdz_agendaDay'] = 'Tag';
$labels['cdz_agendaWeek'] = 'Woche';

$labels['cdz_day_0'] = 'Sonntag';
$labels['cdz_day_1'] = 'Montag';
$labels['cdz_day_2'] = 'Dienstag';
$labels['cdz_day_3'] = 'Mittwoch';
$labels['cdz_day_4'] = 'Donnerstag';
$labels['cdz_day_5'] = 'Freitag';
$labels['cdz_day_6'] = 'Samstag';

$labels['cdz_time_5']  = '05:00';
$labels['cdz_time_6']  = '06:00';
$labels['cdz_time_7']  = '07:00';
$labels['cdz_time_8']  = '08:00';
$labels['cdz_time_9']  = '09:00';
$labels['cdz_time_10'] = '10:00';
$labels['cdz_time_11'] = '11:00';
$labels['cdz_time_12'] = '12:00';
$labels['cdz_time_13'] = '13:00';
$labels['cdz_time_14'] = '14:00';
$labels['cdz_time_15'] = '15:00';
$labels['cdz_time_16'] = '16:00';
$labels['cdz_time_17'] = '17:00';
$labels['cdz_time_18'] = '18:00';

$labels['cdz_timezone'] = 'Zeitzone';
$labels['cdz_tzsupport'] = 'Zeitzonen-Support';
$labels['cdz_rewritetz'] = 'Zeitzone überschreiben';
$labels['cdz_removetz'] = 'Unbekannte Zeitzone entfernen';
?>