<?php
$labels = array();
$labels['caldavzap'] = 'Calendars';
$labels['todo'] = 'Todos';
$labels['reload'] = 'Refresh';

$labels['cdz_standardview'] = 'Default view';
$labels['cdz_weekstart'] = 'First weekday';
$labels['cdz_worktime'] = 'Working hours';
$labels['cdz_weekendays'] = 'Weekend days';

$labels['cdz_month'] = 'Month';
$labels['cdz_multiWeek'] = 'Weeks';
$labels['cdz_agendaDay'] = 'Day';
$labels['cdz_agendaWeek'] = 'Week';

$labels['cdz_day_0'] = 'Sunday';
$labels['cdz_day_1'] = 'Monday';
$labels['cdz_day_2'] = 'Tuesday';
$labels['cdz_day_3'] = 'Wednesday';
$labels['cdz_day_4'] = 'Thursday';
$labels['cdz_day_5'] = 'Friday';
$labels['cdz_day_6'] = 'Saturday';

$labels['cdz_time_5']  = '05:00 am';
$labels['cdz_time_6']  = '06:00 am';
$labels['cdz_time_7']  = '07:00 am';
$labels['cdz_time_8']  = '08:00 am';
$labels['cdz_time_9']  = '09:00 am';
$labels['cdz_time_10'] = '10:00 am';
$labels['cdz_time_11'] = '11:00 am';
$labels['cdz_time_12'] = '12:00 am';
$labels['cdz_time_13'] = '01:00 pm';
$labels['cdz_time_14'] = '02:00 pm';
$labels['cdz_time_15'] = '03:00 pm';
$labels['cdz_time_16'] = '04:00 pm';
$labels['cdz_time_17'] = '05:00 pm';
$labels['cdz_time_18'] = '06:00 pm';
?>